### ISSUE TITLE
train setting

### ISSUE THREAD

**Issue by 2j1ejyu** [rover-xingyu/Ha-NeRF#12]
Hi, thank you for your great work! 
I want to ask if the hyperparameters in the script you wrote as an example were used for your main experiments.

**Comment by rover-xingyu** [comment]
Thanks for your interest! 
Yes, the hyperparameters in the script were used for the main experiments.

**Comment by 2j1ejyu** [comment]
Thanks for your quick reply!
I was asking it since the number of sampling points is only 64+64, which seems to be small for me. So I just wanted to make sure.
And I'm sorry to ask again but It seems that some hparams of your script are different from those of the supplementary. For example, the crop size in your script(min_scale) is 0.5, which is the default value and in your supplementary, it is 0.8.
