### ISSUE TITLE
About Data Preprocessing

### ISSUE THREAD

**Issue by y6216886** [rover-xingyu/Ha-NeRF#15]
![image](https://user-images.githubusercontent.com/38683390/195872065-08d6ed4e-d015-47ad-9dca-2b21af31f875.png)
I Wonder why you use normalize for 2 times?
thanks!

**Comment by y6216886** [comment]
In datasets/phototourism_mask_grid_sample.py

**Comment by rover-xingyu** [comment]
Thanks for pointing this mistake out, we have corrected it [here](https://github.com/rover-xingyu/Ha-NeRF/commit/14a44ca576b3ce6eb54345a37633fab9a657ca73).
