### ISSUE TITLE
How to reproduce the video effects of your project demo.

### ISSUE THREAD

**Issue by y6216886** [rover-xingyu/Ha-NeRF#17]
Hello,
Would you mind teaching me the way of reproducing the effects of your demo on project webpage: [](https://rover-xingyu.github.io/Ha-NeRF/)

**Comment by y6216886** [comment]
For example, the sliding bbox and the transition style along with the rotation of the whole scene.
![image](https://user-images.githubusercontent.com/38683390/204755803-87aa2d5b-ea5f-4599-a4f0-b34cd15e21e4.png)

**Comment by fanegg** [comment]
Hi, the effects are done by merging two videos of different styles via PowerPoint.
