### ISSUE TITLE
 image-dependent transient embedding ‘lτi 

### ISSUE THREAD

**Issue by mowangmodi** [rover-xingyu/Ha-NeRF#22]
hi，xingyu，How is transient embedding obtained,，Is it the following code：
 self.embedding_view = torch.nn.Embedding(hparams.N_vocab, 128)，
I don't understand. Please explain it. Thank you！

**Comment by rover-xingyu** [comment]
Hi, the per-image transient embeddings are randomly initialized and trained by optimizing the objective function.

**Comment by xjchao7** [comment]
> Hi, the per-image transient embeddings are randomly initialized and trained by optimizing the objective function.

Could you please tell me the exact location of the code for transient embeddings? Thank you so so much!

**Comment by rover-xingyu** [comment]
[here](https://github.com/rover-xingyu/Ha-NeRF/blob/3992c90ba8d89f461c758ed76c1b913f5002bfa3/train_mask_grid_sample.py#L74C18-L74C32)
