### ISSUE TITLE
the inputs of transient and appearance embedding

### ISSUE THREAD

**Issue by SensenZhang** [rover-xingyu/Ha-NeRF#23]
Hello, I would like to know the input of transient_embedding and appearance_embedding. Thank you

**Comment by rover-xingyu** [comment]
Hi, the transient embeddings are randomly initialized and trained by optimizing the objective function, and the CNN encoder extracts the appearance embeddings.

**Comment by SensenZhang** [comment]
Thank you for your reply. 
While debugging the code nerf-w, I was puzzled by the 'ts' in the following figure, which when initialized seems to be just a set of integers "img_num*[img_h*img_w]", independent of the characteristics of the image. I want to know the specific meaning of ts and how to obtain it. 
Thank you very much.


谢谢您的回复。我在调试代码nerf-w的过程中，对下图中的 ‘ts’ 感到疑惑，'ts' 在初始化时似乎只是一组 “img_num*[img_h*img_w]” 的整数，与图像的特征并无关系。我想知道ts的具体含义，以及获取的方法。谢谢您！










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rover-xingyu/Ha-NeRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 晚上7:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rover-xingyu/Ha-NeRF] the inputs of transient and appearance embedding (Issue #23)





 
Hi, the transient embeddings are randomly initialized and trained by optimizing the objective function, and the CNN encoder extracts the appearance embeddings.

**Comment by rover-xingyu** [comment]
It denotes the id of the image.

**Comment by SensenZhang** [comment]
I get it. Thank you very much for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rover-xingyu/Ha-NeRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 晚上8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rover-xingyu/Ha-NeRF] the inputs of transient and appearance embedding (Issue #23)





 
It denotes the id of the image.
