### ISSUE TITLE
How to train a model with your own dataset?

### ISSUE THREAD

**Issue by ucbq466** [rover-xingyu/Ha-NeRF#3]
Thanks for sharing the superb code, but I wonder how can I use Ha-NeRF to train a model with my own dataset?

**Comment by rover-xingyu** [comment]
Thanks for your interest! You can follow [these steps](https://github.com/kwea123/nerf_pl#your-own-data) to train with your own data.

**Comment by Duico** [comment]
Hi, I'm wondering why this issue mentions LLFF as a dataset format when this repo does not support it.

**Comment by rover-xingyu** [comment]
Sorry for leading to the misunderstanding,  and to clarify, the key we point out is COLMAP but not LLFF, maybe these [scripts](https://github.com/ashawkey/torch-ngp/tree/main/scripts) are the toolbox you need!
