### ISSUE TITLE
Sample points  for train and test

### ISSUE THREAD

**Issue by lt-xiang** [rover-xingyu/Ha-NeRF#31]
Hi, as the originial NeRF-W said, "During training, 512 points per ray are sampled from each of the coarse and fine models for a total of 1024 points per ray. We double that number during evaluation to 2048."

But the settings are 64(train)  and 256(test) in your code. May I ask why there is a difference ?

**Comment by rover-xingyu** [comment]
Hi! Our training settings are cheaper than the ones used in the original NeRF-W work because of the limited availability of computational resources.
