### ISSUE TITLE
About view consistency loss

### ISSUE THREAD

**Issue by y6216886** [rover-xingyu/Ha-NeRF#4]
Thanks for your inspiring work.

I have a question about figure 3, in which you render I^{r} _{i} based on camera ray and appearance feature of I _{i}. 

I believe that the image I^{i} for generating the appearance feature, and the ground truth image for supervising rendered image I^{r} _{i} should be from the same image domain in which images share the same appearance feature.

However, how to identify the image domain in the given datasets?

I checked the brandenburg_gate dataset, the informations are image name, id, split, and name of dataset.  I wonder which information tells the set of images is from the same image domain?

**Comment by y6216886** [comment]
Ps: From Fig.3,  I _{i} and I^{r} _{i} are images from different camera pose, that is why I ask this question.

**Comment by y6216886** [comment]
![image](https://user-images.githubusercontent.com/38683390/184818789-5b0382c2-68ae-4e39-9636-bff9c33d547c.png)

**Comment by rover-xingyu** [comment]
Thanks for your interest! Maybe you have some misconceptions about the view-consistent loss, there is no ground truth image for supervising the rendered image I^{r} _{i}, and that's why we built the view-consistent loss to supervise the hallucinated image I^{r} _{i}.

**Comment by xuxumiao777** [comment]
Where is the view consistent loss in your code?

**Comment by rover-xingyu** [comment]
https://github.com/rover-xingyu/Ha-NeRF/blob/7d722de779a6e8e526c38b0b384cc3f9a85e2ea5/losses.py#L55C68-L55C85
