### ISSUE TITLE
BlenderDataset预处理

### ISSUE THREAD

**Issue by xiepeter** [rover-xingyu/Ha-NeRF#7]
在BlenderDataset中，看到有随机选取图片的过程，没有明白具体作用，感觉只是shuffle，请教了：
相关代码在blender_mask_grid_sample.py中函数__getitem__中，具体如下：
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/15033583/192956251-2303647f-39e0-4da6-bdf5-b3bd4a785c75.png">

sample_ts是随机选取图片的索引，但rgb_sample_points这个索引的计算没怎么看懂？谢谢指导

**Comment by rover-xingyu** [comment]
The img_sample_points are sampled indexes of a single image, the rgb_sample_points are sampled indexes of the dataset. They are used to sample an image patch from the dataset.
