### ISSUE TITLE
json file

### ISSUE THREAD

**Issue by mowangmodi** [rover-xingyu/Ha-NeRF#8]
How to get a json file

**Comment by rover-xingyu** [comment]
You can download it from the dataset or create it by yourself.

**Comment by mowangmodi** [comment]
> There is no json file in the dataset. Where is the json file

**Comment by rover-xingyu** [comment]
For the Blender dataset, I download the data (include json file) from https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1

**Comment by mowangmodi** [comment]
> 

How can I train? Please tell me the details. I have tried for a long time but failed
